# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            GaoJun's Site
tagline:          'A Jekyll theme'
# baseurl:          

paginate:         5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:           1.0.0
sidebar_home_link:  true
include: [_data]
