# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            GaoJun's Site
tagline:          'A Jekyll theme'
description:      'This is the personal website of GaoJun'
url:              https://gaojun0816.github.io
# baseurl:          

author:
  name:           'Jun Gao'
  #  url:            https://twitter.com/fongandrewc

paginate:         5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:           1.0.0
sidebar_home_link:  true
github:
